### ISSUE TITLE
Fix le design au dezoom

### ISSUE THREAD

**Issue by DYSTOpyy** [insa-sh/insash_website#12]
Faire un sorte que le design du site reste cohérent quand on dézoom.
(A cause du flexbox, les écarts entre les éléments deviennent immenses)
=> suivre le modèle de Louison

```
// pour l'élement qui contient
justify-content: center;
gap: 4vw;

// pour l'élément contenu (valeurs dépendant de l'élément)
max-width: min(25%, 500px);
```

**Comment by DYSTOpyy** [comment]
notamment le header et le footer

**Comment by BillyTheSecond** [comment]
- Header : Done ✅ 
![image](https://github.com/user-attachments/assets/687af3d0-4877-4d8c-a93d-d88a59567108)
- Footer : Déjà fait j'ai l'impression
- page Les membres ✅
