### ISSUE TITLE
Réorganiser les membres du bureau

### ISSUE THREAD

**Issue by Miunn** [insa-sh/insash_website#58]
Réorganiser les membres de façon à ce que la vue mobile affiche Président -> Trésorier -> Secrétaire -> Responsable communication

**Comment by SHAfoin** [comment]
Fix au prochain merge ; temporaire (simple string comparaison avec le rôle), à l'avenir mieux vaut définir un énum role dans la db et filtrer comme ça.
Création d'une nouvelle issue de type "enhancement" relatif à ça.
