### ISSUE TITLE
Les citations trop longues dépasent du layout de la page sur mobile

### ISSUE THREAD

**Issue by Tenclea** [insa-sh/insash_website#65]
Les citations *un peu* longues affichées sur un profil débordent en dehors du layout sur mobile.

PC:
![image](https://github.com/user-attachments/assets/8db0cd74-eaac-4028-ac00-4829f4fec911)

Mobile:
![image2](https://github.com/user-attachments/assets/1993d8dc-38ff-4b31-ae97-6b501b138efa)

**Comment by BillyTheSecond** [comment]
Ok normalement pour ça faut rajouter un word-break en CSS

**Comment by Miunn** [comment]
overflow-wrap: break-word;
ou
word-break: break-all;

**Comment by SHAfoin** [comment]
@BillyTheSecond attention à ce qu'en ajoutant le word-break ça ne fasse pas comme l'issue #55
